### ISSUE TITLE
一点小小的书写错误

### ISSUE THREAD

**Issue by dongsongshan** [xujiajun/PHP-Objects-guidance#2]
您好，写的非常好，非常适合初学者，很感谢您的分享。

PHP对象基础部分有一些书写的小错误，可能会对初学者不太友好 ：）。

1，属性中的first
`public $fristName = "Super";`
改正后
`public $firstName = "Super";`
2，调用属性时，没有括号
`echo $product1->firstName." ".$product1->secondName(); //super U`
改正后
`echo $product1->firstName." ".$product1->secondName; //super U`

**Comment by xujiajun** [comment]
感谢指出。已经更正。
